import Link from "next/link"
import Image from "next/image"
import { ArrowRight, Check, CircleCheck, Code2, Globe2, Handshake, Layers3, LockKeyhole, Server, Sparkles, Wrench } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { PartnerCalculator } from "@/components/partner-calculator"

const steps = ["You acquire the contractor", "You offer a website", "They complete your branded intake", "We build and launch behind the scenes", "You bill the client and retain the spread"]
const handled = ["Custom design and build", "Hosting, SSL, and deployment", "Infrastructure management", "Mobile-responsive implementation", "Contact forms and core site setup", "Reasonable ongoing content updates"]
const partnerOwns = ["The customer relationship", "The retail price", "Customer billing", "The partner-facing experience"]
const faqs = [
  ["Will my customer know Cyberhawk is involved?", "No. This is a white-label fulfillment service. Cyberhawk stays behind the scenes while your agency owns the customer relationship."],
  ["Who owns the domain?", "The contractor owns the domain. Domains are registered through Porkbun, and Cyberhawk can help with selection, DNS, and technical setup."],
  ["Is there a minimum volume requirement?", "There is no hard public minimum at this time. The program is best suited for agencies onboarding multiple new businesses each month."],
  ["What does the monthly fee include?", "The $25 wholesale fee covers the managed website service: hosting, SSL, infrastructure, reasonable content updates, and technical fulfillment."],
]

export function PartnerHome() {
  return <div className="overflow-hidden">
    <section className="relative isolate border-b border-border/50">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_20%,rgba(6,160,199,0.16),transparent_34%),radial-gradient(circle_at_20%_70%,rgba(180,27,227,0.10),transparent_30%)]" />
      <div className="mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-20 md:px-12 md:pb-32 md:pt-28 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
        <div>
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Sparkles className="h-3.5 w-3.5" /> White-label fulfillment</div>
          <h1 className="max-w-4xl text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Add premium websites to your <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">contractor offering.</span></h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Offer professionally built websites under your own brand without hiring developers, managing deployments, or building a web department. We handle fulfillment behind the scenes.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link href="/partner">Become a Partner <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button size="lg" variant="outline" asChild><Link href="/portfolio">See the Work</Link></Button></div>
          <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> $149 setup</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> $25/month wholesale</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> 100% white-label</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-6 rounded-[2rem] bg-primary/10 blur-3xl" /><Card className="relative overflow-hidden border-primary/25 bg-card/90"><CardContent className="p-0"><div className="border-b border-border/70 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Partner fulfillment engine</p><p className="mt-2 text-2xl">Your brand. Your client.</p></div><div className="rounded-xl bg-secondary/10 p-3 text-secondary"><Handshake className="h-6 w-6" /></div></div></div><div className="space-y-3 p-6">{["Partner-branded intake", "Custom website build", "Launch + technical setup", "Managed ongoing service"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-border/60 bg-background/60 p-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">0{index + 1}</span><span className="text-sm">{item}</span><CircleCheck className="ml-auto h-4 w-4 text-primary" /></div>)}</div><div className="bg-gradient-to-r from-primary/10 to-secondary/10 px-6 py-5"><p className="text-sm text-muted-foreground">Most standard sites can be completed in about one week once required information is received.</p></div></CardContent></Card></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-secondary">The opportunity</p><h2 className="mt-4 max-w-xl text-4xl sm:text-5xl">More revenue from customers you already acquire.</h2></div><p className="max-w-2xl text-lg leading-8 text-muted-foreground">New contractors often need a professional website alongside the business infrastructure your agency already helps them secure. Instead of referring that customer elsewhere, add the service to your own offering and keep the relationship in-house.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Card className="bg-card/50"><CardContent className="p-6"><Layers3 className="h-7 w-7 text-primary" /><h3 className="mt-5 text-xl">No web department</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Skip the developers, designers, hosting accounts, and technical overhead.</p></CardContent></Card><Card className="bg-card/50"><CardContent className="p-6"><TrendingIcon /><h3 className="mt-5 text-xl">A useful add-on</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Offer something your contractor customers already need during onboarding.</p></CardContent></Card><Card className="bg-card/50"><CardContent className="p-6"><LockKeyhole className="h-7 w-7 text-secondary" /><h3 className="mt-5 text-xl">You stay in control</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Set your retail pricing, bill your customer, and own the commercial relationship.</p></CardContent></Card></div></section>

    <section id="how-it-works" className="border-y border-border/50 bg-muted/20"><div className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">How it works</p><h2 className="mt-4 text-4xl sm:text-5xl">Simple for your team. Invisible to your customer.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-5">{steps.map((step, index) => <div key={step} className="relative rounded-2xl border border-border/70 bg-card p-5"><span className="text-sm font-bold text-primary">0{index + 1}</span><p className="mt-10 text-sm leading-6">{step}</p>{index < steps.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 text-secondary md:block" />}</div>)}</div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-secondary">Clear economics</p><h2 className="mt-4 text-4xl sm:text-5xl">You set the retail price.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Our wholesale pricing is straightforward: $149 one-time setup per website, then $25 per active website each month. Suggested retail positioning is $199–$299 setup plus $49–$79/month, but your agency controls the final price.</p></div><PartnerCalculator /></div></section>

    <section id="white-label" className="border-y border-border/50 bg-gradient-to-br from-primary/10 via-background to-secondary/10"><div className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="grid gap-14 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">100% white-label</p><h2 className="mt-4 text-4xl sm:text-5xl">Your brand stays front and center.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Cyberhawk is the fulfillment engine behind your offering. We do not compete with you, contact your customer, or attempt to upsell them.</p></div><div className="grid gap-3 sm:grid-cols-2">{partnerOwns.map((item) => <div key={item} className="flex gap-3 rounded-2xl border border-border/70 bg-card/70 p-5"><Check className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm leading-6">You own {item.toLowerCase()}</span></div>)}</div></div></div></section>

    <section id="what-we-handle" className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-secondary">What we handle</p><h2 className="mt-4 text-4xl sm:text-5xl">The technical work stays with us.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Your team offers the service and directs the customer to a partner-branded intake. We take it from there.</p></div><div className="grid gap-3 sm:grid-cols-2">{handled.map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-border/70 bg-card/50 p-4 text-sm"><CircleCheck className="h-4 w-4 text-primary" />{item}</div>)}</div></div></section>

    <section className="border-y border-border/50 bg-muted/20"><div className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">The quality your customers receive</p><h2 className="mt-4 max-w-2xl text-4xl sm:text-5xl">Premium work you can put your brand behind.</h2></div><Button variant="outline" asChild><Link href="/portfolio">Explore portfolio <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["/05_homepage_featuredwork_desktop-mobile-mockup1.png", "Responsive, conversion-ready layouts"], ["/06_homepage_featuredwork_desktop-mobile-mockup2.png", "Distinctive work for service businesses"], ["/07_homepage_featuredwork_desktop-mobile-mockup3.png", "A polished experience across devices"]].map(([src, title]) => <div key={src} className="group overflow-hidden rounded-2xl border border-border/70 bg-card"><div className="relative aspect-[16/10] overflow-hidden"><Image src={src} alt={title} fill className="object-cover transition-transform duration-500 group-hover:scale-105" /></div><p className="p-5 text-sm font-medium">{title}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 md:px-12 md:py-32"><div className="mx-auto max-w-3xl"><p className="text-center text-sm font-semibold uppercase tracking-[0.2em] text-secondary">Partner FAQ</p><h2 className="mt-4 text-center text-4xl sm:text-5xl">The details, clearly.</h2><div className="mt-12 divide-y divide-border/70 rounded-2xl border border-border/70 bg-card/50">{faqs.map(([question, answer]) => <details key={question} className="group p-6"><summary className="cursor-pointer list-none pr-8 text-lg font-semibold marker:hidden">{question}<span className="float-right text-primary transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{answer}</p></details>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-6 pb-24 md:px-12 md:pb-32"><div className="relative overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/15 to-secondary/15 p-8 md:p-14"><div className="relative max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Built for growing agencies</p><h2 className="mt-4 text-4xl sm:text-5xl">Add websites without adding a web department.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Best suited for agencies onboarding multiple new businesses each month. Tell us about your agency and we will walk through the fulfillment model.</p><Button size="lg" className="mt-8" asChild><Link href="/partner">Become a Partner <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
  </div>
}

function TrendingIcon() { return <div className="flex h-7 w-7 items-center justify-center rounded-full bg-secondary/10 text-secondary"><Globe2 className="h-4 w-4" /></div> }

export default PartnerHome
