export const OFFER = {
  setupFee: 149,
  monthlyFee: 25,
  extraRound: 75,
  lateFee: 15,
  retailSetupRange: "$199–$299",
  retailMonthlyRange: "$49–$79",
  firstVersion: "5–7 business days",
  revisionTurnaround: "3 business days",
  feedbackWindow: "5 business days",
  editTurnaround: "2 business days",
  revisionRounds: 2,
  invoiceDay: "1st",
  dueDay: "8th",
  lateAfterDay: "15th",
  noticeDays: 30,
  cancelDays: 60,
  suspendNoticeDays: 5,
  feeChangeNoticeDays: 60,
  archiveDays: 90,
  launchDelayDays: 14,
}
